language: php

cache:
    directories:
        - vendor

matrix:
    # mark as finished before allow_failures are run
    fast_finish: true
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1

# test only master (+ pull requests)
branches:
  only:
    - master

env:
    global:
        - CC_TEST_REPORTER_ID=a707cc8024480e972dfa8aae84ccd2c09198d5f1704807e42c4d1851aae3a7f8

# add php config
before_install:
    - phpenv config-add travis.php.ini
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

# install dependencies
install:
    - composer install

# execute phpunit as the script command
script:
  - ./vendor/bin/phpunit -d memory_limit=-1 --colors -c phpunit.xml.dist --coverage-clover=clover.xml

# disable mail notifications
notification:
  email: false

# reduce depth (history) of git checkout
git:
  depth: 30

# we don't need sudo
sudo: false

# send coverage to codecov.io
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./cc-test-reporter after-build --coverage-input-type "clover" --exit-code $TRAVIS_TEST_RESULT

